### ISSUE TITLE
No instance found for handle left

### ISSUE THREAD

**Issue by dhlim-dev** [SebastianMetzger/angular-material-inbox#1]
index.html
- 23 <md-sidenav class="md-sidenav-left" component-id="left">
+ 23 <md-sidenav class="md-sidenav-left" md-component-id="left">

i used angular-material.0.6.1.js

thank you.

**Comment by SebastianMetzger** [comment]
My bower dependencies require angular-material "~0.5.1"

Have not updated the project since writing the blog post

**Comment by dhawken** [comment]
I'm on 0.5.1 and was also getting this error.  This failed whn my markup referenced md-component-id but works when I use component-id.

**Comment by SebastianMetzger** [comment]
kk, I will look into it in the next couple of days and clean things up while upgrading to the latest angular-material version.

I actually did not expect so much interest in this project, which is cool =)

**Comment by dhawken** [comment]
Not a lot of angular material ref project type stuff out there yet - i think you would be surprised at the interest level!

**Comment by James-1064** [comment]
Thanks for the sample, but the toolbar and side nav are not working with the latest version of the frameworks. I'm using angular 1.3.8 and Material 0.8rc1. there have probably been a number of breaking changes since Material 0.5.1... Would be great to see an updated version, thanks again for your time and effort.

**Comment by SebastianMetzger** [comment]
Finally had some time to update the project, it now is based on angular-material 0.8.x

**Comment by Luxiyalu** [comment]
For anyone else who's getting the "No instance found for handle left" error: it means the `$mdSidenav` instance you're calling (`'left'`, in this case) has not yet been initialised upon your call. See [this](http://luxiyalu.com/angular-material-no-instance-found-for-handle-left/).

Use this instead:

```
$mdComponentRegistry.when('left').then(function(it){
  it.close();
});
```

It'd be great if we could have a way to check if the instance is out there yet without having to log error.

**Comment by mattiLeBlanc** [comment]
@Luxiyalu thanks for great work around which is still elegant!
