### ISSUE TITLE
Update bootstrap instructions in README

### ISSUE THREAD

**Issue by cpursley** [SebastianMetzger/angular-material-inbox#2]
I'm getting a `Warning: Task "jshint:all" failed` notification when running `Grunt`

What are the specific steps to run this example?

**Comment by SebastianMetzger** [comment]
Just tested it again, you are right, the default grunt target ist not working, but actually building the project is not necessary.

Just start a web server in the folder, it is only a front end mock up project anyway. =)

**Comment by cpursley** [comment]
Ah, so any web server?

**Comment by SebastianMetzger** [comment]
If you have python installed try this in the project root:

```
python -m SimpleHTTPServer
```

or

```
python -m http.server
```
