### ISSUE TITLE
 General FAQ

### ISSUE THREAD

**Issue by deepika-Gopala** [SebastianMetzger/angular-material-inbox#4]
Hi,

This is not a issue, I just wanted to know why python is necessary to be installed to run this project , can we run with any other server, if its necessary, do we as a devEloper learn about python? for any further feature implementations or enhancements?

**Comment by SebastianMetzger** [comment]
You can use any web server to serve the project, python is just the example.

I believe this project provides similar functionality with a NodeJS HTTP Server:
https://github.com/indexzero/http-server
